# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  config.ssh.insert_key = false
   config.ssh.forward_x11 = true
  config.vbguest.auto_update = true

=begin
  config.vm.define :webServer do |server_config|
   server_config.vm.box = "ubuntu/trusty64"
   server_config.vm.hostname = "1webServer"
   server_config.vm.network :private_network, ip: "192.168.56.222"
    server_config.vm.synced_folder "/afs/.ist.utl.pt/users/1/9/ist426019/Vagrant/shared/configs", "/home/vagrant/.core/configs"
   server_config.vm.synced_folder "/afs/.ist.utl.pt/users/1/9/ist426019/Vagrant/shared/myServices", "/home/vagrant/.core/myservices"
   server_config.vm.provider "virtualbox" do |vb|
    vb.name = "1webServer"
    opts = ["modifyvm", :id, "--natdnshostresolver1","on"]
    vb.customize opts
    vb.memory = "2048"
   end
   server_config.vm.provision :shell, path: "boostrap-core.sh"
  end


  config.vm.define :webClient do |client_config|
   client_config.vm.box = "ubuntu/trusty64"
   client_config.vm.hostname = "1webClient"
   client_config.vm.network :private_network, ip: "192.168.56.200"
    client_config.vm.synced_folder "/afs/.ist.utl.pt/users/1/9/ist426019/Vagrant/shared/configs", "/home/vagrant/.core/configs"
   client_config.vm.synced_folder "/afs/.ist.utl.pt/users/1/9/ist426019/Vagrant/shared/myServices", "/home/vagrant/.core/myservices"
	client_config.vm.synced_folder "/afs/.ist.utl.pt/users/1/9/ist426019/Vagrant/shared/shared_web", "/home/vagrant/shared_web"
   client_config.vm.provider "virtualbox" do |vb|
    vb.name = "1webClient"
    opts = ["modifyvm", :id, "--natdnshostresolver1","on"]
    vb.customize opts
    vb.memory = "2048"
   end
   client_config.vm.provision :shell, path: "boostrap-core.sh"
  end
=end

  #CORE VM  configuration
	config.vm.define :core do |core_config|
		core_config.vm.box = "ubuntu/trusty64"
		core_config.vm.hostname = "core"
		core_config.vm.network :private_network , ip: "192.168.56.200"
		core_config.vm.synced_folder "shared/configs","/home/vagrant/.core/configs"
		core_config.vm.synced_folder "shared/shared_web","/home/vagrant/shared_web"
		core_config.vm.synced_folder "shared/myServices","/home/vagrant/.core/myservices"
		core_config.vm.provider "virtualbox" do |vb|
		vb.name = "core"
		opts = ["modifyvm", :id , "--natdnshostresolver1", "on"]
		vb.customize  opts
		vb.memory = "2048"
		end
		core_config.vm.provision :shell , path: "bootstrap-core.sh"
	end

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # NOTE: This will enable public access to the opened port
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine and only allow access
  # via 127.0.0.1 to disable public access
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  # config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
  # end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
config.vm.provider :virtualbox do |vb|
  vb.gui = false
end
end